### ISSUE TITLE
Bug Report.

### ISSUE THREAD

**Issue by rocky-lq** [bigcode-project/astraios#3]
https://github.com/bigcode-project/astraios/blob/a133ecca906ecc9ac4ec23fba969d06219a9e6b0/training/finetune.py#L372 There is a bug in this line: 
`TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'.`
It should return a string in `print_trainable_parameters` function.

**Comment by terryyz** [comment]
Hi,

Thanks for the note! I'll change the return type of `print_trainable_parameters` to string.

Cheers

**Comment by terryyz** [comment]
Fixed.
