### ISSUE TITLE
Outputs problem

### ISSUE THREAD

**Issue by SummCoder** [bigcode-project/astraios#4]
Why many predictions in the clone detection task are -1,like this `"ID": 0, "prediction": "-1", "true_label": "0"`

**Comment by terryyz** [comment]
Hi,

You can check how we denote the "0", "1," and "-1" to the predictions in this [notebook](https://github.com/bigcode-project/astraios/blob/main/evaluation/eval_code_comprehension.ipynb). Essentially if we can extract the specific keywords from the generations, we consider the outputs valid. This is not a very robust method. The best way is to manually check each of them, which is quite costly.

Cheers
