### ISSUE TITLE
AATK evaluation process_results is missing

### ISSUE THREAD

**Issue by adiprasad** [bigcode-project/astraios#7]
Duplicate of https://github.com/bigcode-project/bigcode-evaluation-harness/issues/197

the [process_results](https://github.com/bigcode-project/bigcode-evaluation-harness/blob/astraios/bigcode_eval/tasks/aatk.py#L130-L131) functions to get the metrics is missing 

Any pointers on this ? Is there any other script for AATK eval that I'm not aware of ?

**Comment by terryyz** [comment]
Hi,

There is an evaluation repo provided by the authors of the benchmark: https://github.com/moyix/AsleepKeyboardDataset

We mainly rely on the evaluation scripts provided by them.

Cheers
